--------------------------------------------------------
--  File created - Wednesday-October-30-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SIGNON
--------------------------------------------------------

  CREATE TABLE "SYS"."SIGNON" 
   (	"ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(40 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"SIGNON_NAME" VARCHAR2(25 BYTE), 
	"SIGNON_PASSWORD" VARCHAR2(60 BYTE), 
	"SIGNON_ROLE" VARCHAR2(100 BYTE), 
	"SIGNON_ENABLED" CHAR(1 BYTE), 
	"MOBILE_NO" NUMBER(*,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_BY" NUMBER, 
	"UPDATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" NUMBER, 
	"SIGNON_NON_EXPIRED" CHAR(1 BYTE), 
	"PASSWORD_NON_EXPIRED" CHAR(1 BYTE), 
	"SIGNON_NON_LOCKED" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.SIGNON
SET DEFINE OFF;
Insert into SYS.SIGNON (ID,FIRST_NAME,LAST_NAME,EMAIL,SIGNON_NAME,SIGNON_PASSWORD,SIGNON_ROLE,SIGNON_ENABLED,MOBILE_NO,CREATED_DATE,CREATED_BY,UPDATED_DATE,UPDATED_BY,SIGNON_NON_EXPIRED,PASSWORD_NON_EXPIRED,SIGNON_NON_LOCKED) values (100,'INDERJIT','SANHOTRA','email@one.com','TEST','$2a$10$WLW6uPamKukW8CdKB38lJOVFFr4ZoporD2IW3xLYstxAM2oxi4WIS','ROLE_ADMIN,ROLE_USER','1',7738535998,to_timestamp('01-01-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),100,to_timestamp('30-10-19 08:00:10.729000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),100,'1','1','1');
--------------------------------------------------------
--  DDL for Index SIGNON_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."SIGNON_INDEX1" ON "SYS"."SIGNON" ("ID", "SIGNON_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SIGNON
--------------------------------------------------------

  ALTER TABLE "SYS"."SIGNON" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SIGNON" MODIFY ("SIGNON_NON_EXPIRED" NOT NULL ENABLE);
